---
title: "General Concepts"
---

### Admins and Site Admins
There are two types of admins in MISP: Admins (also referred to as org admins) and Site Admins. Whilst the former can only do some limited administration of users of his/her own organisation, site admins have access to all of the features and data of the system. They are in charge of making sure that the system runs correctly and the maintenance of MISP.

### Background Jobs
A lot of the heavier tasks are a burden to users, in that their actions can cause long delays (and in some cases timeouts) while the application logic is executing. To alleviate this, long processes have been (if enabled) moved to background jobs, meaning that their execution happens asynchronously in the background, allowing the user to freely interact with the platform whilst the request is being processed. In MISP 2.5 this is the standard execution model, provided by the SimpleBackgroundJobs system (Supervisor + Redis).

### Correlation
Correlation is the automatic linking of events that share the same piece of information. Whenever an attribute value that a user is allowed to see also appears on another event, MISP creates a correlation between the two, surfacing the relationship in the event view (and as a graph). This is what turns a collection of individual events into a navigable web of related intelligence and is the basis for [pivoting](#pivoting). Correlation can be disabled per attribute (the "disable correlation" flag), suppressed for noisy values through correlation exclusions and correlation rules, and tuned by the correlation engine — see the [Administration](../administration/index.qmd) chapter.

### Distribution levels
Every event, attribute, and object carries a distribution setting that controls how far it may spread when instances synchronise. The levels are: **Your organisation only** (never leaves your instance/organisation), **This community only** (stays on this instance and its direct connections but is not re-shared onwards), **Connected communities** (may be shared one hop further, to the communities your community connects to), **All communities** (freely shareable) and **Sharing group** (visible only to an explicitly enumerated set of organisations/instances). Attributes and objects can additionally **inherit** the distribution of their parent event. Distribution degrades by one step on each synchronisation hop, so information cannot travel further than its originator intended. Distribution is covered in depth in the [Sharing](../sharing/index.qmd) chapter.

### MISP Instance
A MISP instance is an installation of the MISP software and the connected database. All the data visible to the users is stored locally in the database and data that is shareable (based on the distribution settings) can be synchronised with other instances via the Sync actions. The instance that you are reading this manual on will be referred to as "this instance" or "your instance". The instances that your instance synchronises with will be referred to as "remote instances".

### Pivot path
The (branching) path taken by a user from event to event while following correlation links. This is represented by the branching graph in the event view.

### Pivoting
The act of navigating from event to event through correlation links.

### Proposals
Each event can only be directly edited by users of the original creator organisation (and site admins). However, if another organisation would like to amend an event with extra information on an event, or if they'd like to correct a mistake in an attribute, they can create a Proposal. These proposals could then be accepted by the original creator organisation. These proposals can be pulled to another server, allowing users on connected instances to propose changes which then could be accepted by the original creators on another instance (and subsequently pushed back).

### Publishing
When an event is first created by a user, it is visible to everyone on the instance based on the access rights ("Your organisation only" events will not be visible to users of other organisations), but they will not be synchronised and they won't be exportable. For this, a user with publishing permission of the organisation that created the event has to publish the event. The system will then inform all the users of the instance that are subscribing to e-mail notifications and who have access to view the published event via an e-mail.

### Pull
Pulling is the process of using the configured sync user on a remote instance to REST GET all of the accessible data (based on the distribution rights) to your instance and store it.

### Push
Pushing is the process of using a configured instance link to send an event or all accessible events (limited by the distribution rights) through the REST interface to a remote instance.

### Scheduled Tasks
Certain common tasks can be scheduled for a later execution or for regular recurring executions. These tasks currently include caching all of the export formats, pulling from all eligible instances and pushing to all eligible instances.

### Sync User
A user of a role that grants sync permissions, these users (and their authentication keys) are used to serve as the points of connection between instances. Events pushed to an instance are pushed to a sync user, who then creates the events on the remote instance. Events pulled are added by the sync user that is used to connect the remote instance to your instance. As an administrator, keep in mind that a sync user needs auth key and publish permissions, has to have undergone the mandatory password change and has to have accepted the Terms of Use in order for the sync to work. Please make sure that all of these steps are taken before attempting to push or pull.

### Synchronisation
What we call synchronisation is an exchange of data between two (or more) MISP instances through our pull and push mechanisms.

### Tagging
Users with tagging rights can assign various dynamically created tags to events, allowing an arbitrary link between events to be created. It is possible to filter events based on these tags and they can also be used to filter events for the automation.

### Templating
Users with templating rights can create easy to fill forms that help with the event creation process.
